<?php

/**
 * @file
 * Octopus helper functions.
 */

/**
 * Implements hook_menu_alter().
 */
function octopus_helper_menu_alter(&$items) {
  $items['node/%/group']['title'] = t('Channel');
}

/**
 * Implements hook_field_info_alter().
 */
function octopus_helper_field_info_alter(&$info) {
  // Add a setting to all field types.
  $info['group']['label'] = t('Channel');
  $info['group']['description'] = t('This field stores channels associated with the content.');
}

/**
 * Implements hook_field_widget_info_alter().
 */
function octopus_helper_field_widget_info_alter(&$info) {
  // Add a setting to all field types.
  $info['group_audience']['label'] = t('Channel audiance');
  $info['group_audience_autocomplete']['description'] = t('Display the list of referenceable channels as a textfield with autocomplete behaviour.');
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function octopus_helper_field_formatter_info_alter(&$info) {
  // Add a setting to all field types.
//  $info['group_audience']['label'] = t('Channel audiance');
//  $info['group_audience_autocomplete']['description'] = t('Display the list of referenceable channels as a textfield with autocomplete behaviour.');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function octopus_helper_form_video_node_form_alter(&$form, &$form_state) {
  $form['group_audience']['und']['#options']['My channels'] = $form['group_audience']['und']['#options']['My groups'];
  unset($form['group_audience']['und']['#options']['My groups']);
}