<?php

/**
 * @file
 * JWPlayer formatter for use with filefields.
 */

/**
 * Implements hook_field_formatter_info().
 */
function jwplayer_field_formatter_info() {
  return array(
    'jwplayer' => array(
      'label' => 'JWPlayer',
      'field types' => array('file'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function jwplayer_theme() {
  return array(
    'jwplayer_formatter_jwplayer' => array(
      'render element' => 'element',
    ),
    'jwplayer' => array(
      'variables' => array('items' => NULL, 'player_id' => NULL, 'attributes' => NULL)
    ),
  );
}

/**
 * Theme function; Convert integers to their full text representation.
 */
function theme_jwplayer_formatter_jwplayer($variables) {
  $element = $variables['element'];
  if (!isset($element['#item']['uri'])) {
    return '';
  }

  // Build the jwplayer configuration array. And then use it to add the
  // necessary javascript to the page. Done in two steps to make it easier for
  // a theme to add additional configuration for JWPlayer.
  $config = jwplayer_player_config($element);
  $file_url = file_create_url($element['#item']['uri']);
  $config['file'] = $file_url;

  jwplayer_add_player($element, $config);
  $output = '<video id="' . $element['#field_name'] . '_player" src="' . $file_url . '" controls="controls" height="' . $config['height'] . '" width="' . $config['width'] . '"></video>';
  return $output;
}

/**
 * Theme function for jwplayer to integrate with other module
 */
function theme_jwplayer($variables) {
  $element = $variables['item'];
  $element['player_id'] = $variables['player_id'];
  if (!isset($element['uri'])) {
    return '';
  }

  // Build the jwplayer configuration array. And then use it to add the
  // necessary javascript to the page. Done in two steps to make it easier for
  // a theme to add additional configuration for JWPlayer.
  $config = jwplayer_player_config($element);
  $file_url = file_create_url($element['uri']);
  $config['file'] = $file_url;
  // @todo add array merge
  $config['width'] = $variables['attributes']['width'];
  $config['height'] = $variables['attributes']['height'];
  $config['flashplayer'] = isset($variables['attributes']['flashplayer']) ? $variables['attributes']['flashplayer'] : url(drupal_get_path('module', 'jwplayer') . '/jwplayer/player.swf', array('absolute' => TRUE));
  $config['stretching'] = isset($variables['attributes']['stretching']) ? $variables['attributes']['stretching'] : 'fill';
  $config['bufferlength'] = isset($variables['attributes']['bufferlength']) ? $variables['attributes']['bufferlength'] : 10;
  if ($element['image'])
    $config['image'] = file_create_url($element['image']['uri']);

  jwplayer_add_player($element, $config);
  $output = '<video id="' . $variables['player_id'] . '_player" src="' . $file_url . '" controls="controls" height="' . $config['height'] . '" width="' . $config['width'] . '"></video>';
  return $output;
}

/**
 * Add the javascript necessary for embedding the JWPlayer onto the page.
 *
 * @param $element
 *   The CCK/filefield element.
 * @param $config
 *   An associative array of containing data to be passed to the jwplayer()
 *   javascript method as configuration parameters.
 */
function jwplayer_add_player($element, $config) {
  drupal_add_js(drupal_get_path('module', 'jwplayer') . '/jwplayer/jwplayer.js');
  drupal_add_js(drupal_get_path('module', 'jwplayer') . '/jwplayer_behaviors.js');

  // Convert $config array to Drupal.settings variables.
  $config = array(
    'jwplayer' => array(
      $element['player_id'] . '_player' => $config,
    // @todo - add error logging with ajaxlog module.
    //'error_log' => variable_get('cloudfrontvideo_error_log_enabled', TRUE),
    ),
  );
  drupal_add_js($config, 'setting');
}

/**
 * Helper function to build a $config array for JWPlayer.
 */
function jwplayer_player_config($element) {
  // Setup some sane defaults. These can be overriden by another module using
  // hook_jwplayer_config_alter(&$config).
  $config = array(
    'flashplayer' => url(drupal_get_path('module', 'jwplayer') . '/jwplayer/player.swf', array('absolute' => TRUE)),
    'bufferlength' => 10,
    // @todo: these should be configurable
    'height' => 480,
    'width' => 854,
    'stretching' => 'fill',
  );

  // Allow other modules to alter the $config array.
  drupal_alter('jwplayer_config', $config, $element);

  return $config;
}
