<?php

/**
 * Implements hook_install().
 */
function octopus_taxonomy_install() {
  // create terms
  $vid = db_query("SELECT vid FROM {taxonomy_vocabulary} WHERE machine_name = :machine_name", array(':machine_name' => 'categories'))->fetchField();
  $terms = array(
    array(
      'name' => 'Educational'
    ),
    array(
      'name' => 'Comedy'
    ),
  );
  foreach ($terms as $term) {
    $term['vid'] = $vid;
    taxonomy_term_save($term);
  }
}
